### PR TITLE
fix: init shape var & skip CDE CreateImage for heisenbug reason

### PR DESCRIPTION
**Pull request by askonev**
In github Actions, the test crash is repeated regularly but not always (heisenbug). The error does not occur on a clean machine and docker container with limits on cpu and memory. It is also reproduced if you install a `base64` image, which means that these are not network problems.

```bash
Failures:

  1) Api section tests Api | CreateImage method
     Failure/Error: expect(drawing.graphic.data.path_to_image.file_reference.content.length).to be > 1000

     NoMethodError:
       undefined method `length' for nil:NilClass
     # ./spec/docx/smoke/api_base_spec.rb:52:in `block (2 levels) in <top (required)>'
```

```docker
docker run --name 1g1cpu \
            --cpus="1" \
            --memory=1g \
            --memory-swap 0 \
           test
```

I will update ruby to 3.2.2 for centos and repeat the tests

### CODE REVIEW

**Review by alinasafonova — APPROVED** [review]

**Comment by VitaliySerov** [comment]
> I will update ruby to 3.2.2 for centos and repeat the tests

@askonev BTW this is not an easy task - it's currently blocked by this:

https://github.com/ONLYOFFICE/doc-builder-testing/issues/1029

I've pushed the code to 3rdparty repo to provide those builds, but seems no one cares

**Comment by askonev** [comment]
@VitaliySerov Yes, I saw that the repository maintainer stopped actively supporting the project.

A simple solution would be to install the latest beta version that is available
[ruby-3.2.2-1.el7.centos.x86_64.rp](https://github.com/feedforce/ruby-rpm/releases)

And then look for a solution

**Comment by VitaliySerov** [comment]
@askonev Right now we're usinng 3.2.0:

https://github.com/ONLYOFFICE/doc-builder-testing/blob/master/dockerfiles/centos-7/Dockerfile#L5

it can be update for latest avialabe build v3.2.2-1 - without any problems
Actually I think you should do it :)

But if we need to update to latest ruby 3.3 it will be a problem right now, yeah

**Comment by askonev** [comment]
@VitaliySerov The repository may not be able to continue working because support for CentOS Stream 8 and CentOS Linux 7 ends on May 31, 2024.

I think the task of migrating to CentOS Stream 9 of our tests will solve the problem with migrating to ruby 3.3.*

https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/

**Comment by VitaliySerov** [comment]
Yep, probably migrate tests to centos 9 stream is good idea

I think centos 7 will be alive for long years again but seems you're right it's like 2 months until EOL, wow how time goes...

**Pull request merged**
