### PR TITLE
feature: commented intrs for web buidler run

### PR DESCRIPTION
**Pull request by askonev**
A similar solution if you have to work locally a lot

https://github.com/ONLYOFFICE-QA/convert-service-testing/blob/67700cc710e7b2ce156f2c8f95c3addf9044a2c4/spec/spec_helper.rb#L17

### CODE REVIEW

**Review by alinasafonova — APPROVED** [review]

**Comment by VitaliySerov** [comment]
Question:

Are we 100% sure it's the same?

We're using this code to access docbuilder endpoint - `http://{docserver_url}/docbuilder`

But I don't see a single mention of `docbuilder` string in the `convert-service-testing`

Maybe some misunderstanding happens to place?
/docbuilder endpoint can convert files, but also it can generate office files remotely

**Comment by askonev** [comment]
> Question:
> 
> Are we 100% sure it's the same?
> 
> We're using this code to access docbuilder endpoint - `http://{docserver_url}/docbuilder`
> 
> But I don't see a single mention of `docbuilder` string in the `convert-service-testing`
> 
> Maybe some misunderstanding happens to place? /docbuilder endpoint can convert files, but also it can generate office files remotely

The solution is similar in the sense that it is convenient to add the configuration manually. That is, a specific indication of where the entry point is located

**Comment by VitaliySerov** [comment]
> > Question:
> > Are we 100% sure it's the same?
> > We're using this code to access docbuilder endpoint - `http://{docserver_url}/docbuilder`
> > But I don't see a single mention of `docbuilder` string in the `convert-service-testing`
> > Maybe some misunderstanding happens to place? /docbuilder endpoint can convert files, but also it can generate office files remotely
> 
> The solution is similar in the sense that it is convenient to add the configuration manually. That is, a specific indication of where the entry point is located

Ah sorry, my bad :)

I read this PR wrong, I fought we commented out something, but actually we added comment to easy uncommenting locally if needed

Sorry, totally my bad

**Comment by askonev** [comment]
@VitaliySerov You are right, `convert-service-testing` a separate prj, the functionality of which differs from the functionality provided by the `docbuilder` path

But my idea is to show the engineers running the `doc-builder-testing` project how the environment works intuitively.

**Pull request merged**
