### PR TITLE
[7.2] Smoke tests on Char Style config methods. Bug #54039

### PR DESCRIPTION
**Pull request by askonev**

### CODE REVIEW

**Review by ShockwaveNN — CHANGES_REQUESTED** [review]
I think we need to add `# TODO:` statement to this test that it needs to be redone via the native `ooxml_parser` test but it requires a lot of time

**Review by l8556 — APPROVED** [review]

**Comment by askonev** [comment]
> 

Maybe issue for this project or ooxml_parser pr?

**Comment by ShockwaveNN** [comment]
> 
Maybe issue for this project or ooxml_parser pr?

Yeah, I think so

**Comment by askonev** [comment]
Add bug `#59325`

Merge after the fix

**Review by ShockwaveNN — APPROVED** [review]

**Pull request merged**
